name: run main.py

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  schedule:
    # Run everyday of the month except at saturday at 7PM
    - cron: 0 19 * * 0-5

jobs:
  build:
    runs-on: windows-latest
    steps:
      # checkout the repository content to github runner
      - name: checkout repo content
        uses: actions/checkout@v3

      # setting up python
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      # Running pytest
      - name: Test with pytest
      run: |
        pytest

      # Executing the python script
      - name: execute the script
        run: python main.py

      # Generated logs and datas, and commit and push in github
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git congif --local user.name "Github Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs, and uploaded datas" --allow-empty)

      # Pushing the changes
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          brandh: master
