name: run main.py

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  schedule:
    # Run everyday of the month except at saturday at 7PM
    - cron: 0 19 * * 0-5

jobs:
  build:
    runs-on: windows-latest
    steps:
      # checkout the repository content to github runner
      - name: checkout repo content
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      # setting up python
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: install python packages
        run: python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Executing the python script
      - name: execute the script
        run: python main.py

      # Generated logs and datas, and commit and push in github
      - name: commit files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs, and uploaded datas" --allow-empty)

      # Pushing the changes
      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
